name: django-ci

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: set up python
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          python3 -m pip install --upgrade pip
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run migrations
        run: |
          python manage.py migrate
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: build  and push docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/django-app:latest .
          docker push ghcr.io/${{ github.repository_owner }}/django-app:latest
      - name: run tests
        run: |
          python manage.py test


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: ec2 login
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ec2-15-207-84-187.ap-south-1.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ghcr.io/${{ github.repository_owner }}/django-app:latest
            docker stop django-app || true
            docker rm django-app || true
            docker run -d --name django-app -p 8000:8000 ghcr.io/${{ github.repository_owner }}/django-app:latest
            echo "Deployment completed successfully"
